tasks:
  - name: Python Dependencies
    before: pip install -r requirements.txt

# We have also customized the environment so that whenever we run an app on port 8000 it
# is automatically made public and is opened up in a browser.
ports:
  - name: API
    description: Preview changes to your application
    port: 8000-9000
    onOpen: open-browser
    visibility: public